<?php

namespace App\Http\Requests;

use Illuminate\Contracts\Validation\ValidationRule;
use Illuminate\Foundation\Http\FormRequest;

class StoreCaseModelRequest extends FormRequest
{
    public function authorize(): bool
    {
        return $this->user()?->can('cases.create') ?? false;
    }

    /**
     * The case_code is generated by the service; status/date_opened/worker
     * default there too.
     *
     * @return array<string, ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return [
            'patient_id' => ['required', 'exists:patients,id'],
            'assigned_user_id' => ['nullable', 'exists:users,id'],
            'case_type' => ['required', 'string', 'max:255'],
            'priority_level' => ['required', 'string', 'max:255'],
            'admission_type' => ['required', 'string', 'max:255'],
            'status' => ['nullable', 'string', 'max:255'],
            'date_opened' => ['nullable', 'date'],
        ];
    }
}
