<?php

namespace App\Http\Requests;

use App\Enums\CardColor;
use Illuminate\Contracts\Validation\ValidationRule;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class StoreCaseModelRequest extends FormRequest
{
    public function authorize(): bool
    {
        return $this->user()?->can('cases.create') ?? false;
    }

    /**
     * The case_code is generated by the service; status/date_opened/worker and
     * created_by default there too. When a transaction_id is given the service
     * snapshots admission_type from the encounter, so it is only required when no
     * encounter is supplied. created_by is never accepted from the client.
     *
     * @return array<string, ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return [
            'patient_id' => ['required', 'exists:patients,id'],
            'assigned_user_id' => ['nullable', 'exists:users,id'],
            'case_type' => ['required', 'string', 'max:255'],
            'priority_level' => ['required', 'string', 'max:255'],
            'admission_type' => ['required_without:transaction_id', 'string', 'max:255'],
            'transaction_id' => ['nullable', 'integer'],
            'transaction_type' => ['nullable', 'string', 'max:255'],
            'card_color' => ['nullable', Rule::enum(CardColor::class)],
            'status' => ['nullable', 'string', 'max:255'],
            'date_opened' => ['nullable', 'date'],
        ];
    }
}
